---
title: "IrisIneke.Rmd"
author: "Iris Ineke"
date: "2024-10-17"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Zondag 13 oktober:

Ik moet voor het plan van aanpak de samples uitzoeken. De verschillende
samples:

-   Baseline_RNAseq (4)

-   NonTreated_RNAseq (6)

-   Treated_RNAseq (6)

-   NSG_Baseline_000_RNAseq (5)

-   NSG_Non-Treatment_000_RNAseq (5)

-   NSG_Entinostat_000_RNAseq (5)

-   Baseline_TCRseq (6)

-   NonTreated_TCRseq (6)

-   Treated_TCRseq (6)

Er zijn dus drie groepen:

-   RNAseq
-   NSG_RNAseq
-   TCRseq

en elke groep bestaat uit:

-   Baseline
-   Non_treated
-   Treated

De sample nummers van de TCRseq en de RNAseq zijn allebei in de 400, Dus
ik vermoed dat ze twee sequence techieken op dezelfde samples hebben
uitgevoerd.

Wat is het verschil tussen de TCRseq, RNAseq en NSG_RNAseq:

-   RNAseq: meet de genexpressie (onder bepaalde omstandigheden)
-   TCRseq: meet de reactie van het immuumsysteem (door te kijken naar
    de hoeveelheid T-celreceptors ( cellen die het antigenen herkennen))
-   NSG_RNAseq: NSG-muizen zijn muizen die een zwak immuumsysteem hebben
    en daardoor gebruikt worden om menselijke cellen in te enten (zonder
    dat het immuumsysteem van de muis ze afstoot).

Wat is het verschil tussen de Baseline, Non_treated en Treated:

-   Baseline is voor de tumor
-   Non_treated is na de tumor zonder entinostat
-   Treated is na de tumor met entinostat

quality control: welke tools gaan we gebruiken en waarom: - trimmomatic:
om de lage kwaliteit reads van het sequencen eruit te halen. Waarom: Om
foutieve conclusies door foutieve data later te voorkomen (als je data
gebruikt die niet klopt, trek je uit die data ook conclusies die niet
overeenkomen met de werkelijkheid). - fastqc: geeft een rapport met de
kwaliteit van de data. Waarom: Hieruit kun je bepalen wat je eventueel
wilt aanpassen met Trimmomatic. - multiqc: voegt alle fastqc rapporten
van samples samen tot een rapport. Waarom: Zo kun je makkelijker de
resultaten van fastqc van alle samples bekijken.

! Presenteren:

-   samples met nsg enzo (tabel leveren aan Ramon)
-   quility control (bulletpoints: trimmomatic, fastqc, multiqc)

## Maandag 14 oktober:

Alles uitgeschreven voor de presentatie en het plan van aanpak:\

Tabel van de samples (van de Transcriptomics):\

(!tabel doet raar met knitten)\


|                | **Baseline** | **Non_treated** | **Treated** | 
|----------------|--------------|-----------------|-------------| 
| **RNAseq**     |       4      |        6        |      6      | 
| **NSG_RNAseq** |       5      |        5        |      5      | 
| **TCRseq**     |       6      |        6        |      6      | 



**Samples**\
Er zijn voor het transcriptomics gedeelte in totaal 49 samples. Deze
samples bestaan uit drie groepen; RNAseq, NSG_RNAseq en TCRseq. En al
deze groepen bestaan uit baseline, non_treated en treated. De RNAseq en
de TCRseq zijn waarschijnlijk uitgevoerd op dezelfde samples, aangezien
de identificatienummers overeenkomen met elkaar. De NSG_RNAseq zijn een
andere soort samples. NSG staat in dit geval voor een soort muis die
gekweekt wordt en vaak voor onderzoek wordt gebruikt. Het immuunsysteem
van deze muis is namelijk zeer zwak of helemaal afwezig. Hierdoor is de
NSG-muis perfect om menselijke cellen in te enten, omdat het
immuunsysteem van de muis de cellen niet goed kan afbreken. Hierdoor
kunnen ze in het onderzoek kijken welk effect de mutatie op menselijke
cellen heeft zonder menselijke proefpersonen te hoeven gebruiken. Met de
RNA-sequencing wordt er gekeken naar de genexpressie onder bepaalde
omstandigheden. In dit geval dus zonder mutatie (baseline) met mutatie
(non_treated) en met mutatie en medicatie (treated). De TCR-sequencing
meet de reactie van het immuunsysteem door te kijken naar de hoeveelheid
T-celreceptors (cellen die het antigen herkennen).

**quality control**\
We gaan Fastqc en Multiqc gebruiken om te bepalen wat we willen
verbeteren aan de data. Dit doen we door middel van het rapport dat uit
Multiqc komt (wat een samenvatting maakt van alle rapporten die uit
Fastqc komen). Hierna gaan we Trimmomatic gebruiken om de lage kwaliteit
reads van het sequencen eruit te halen. Dit doen we om foutieve
conclusies door foutieve data later te voorkomen. Als je data gebruikt
die niet klopt, trek je immers (uit die data) ook conclusies die niet
overeenkomen met de werkelijkheid. Hierna voeren we nog een keer Fastqc
en Multiqc uit om te kijken of Trimmomatic voldoende verbeterd heeft.
Als er uit dit rapport blijkt dat de data nog niet genoeg is opgeschoond
zullen we nog een keer Trimmomatic moeten gebruiken totdat we tevreden
zijn.

## woensdag 16 oktober

## quality control:

FastQC en multiQC uitgevoerd op de data (duurt erg lang, rekening mee
houden in planning).

Uit het multiqc rapport blijkt dat 'Per Base Sequence Content', 'Per
Sequence GC Content' en 'Sequence Duplication Levels' verbeterd kunnen
worden.

Trimmomatic uitgevoerd (instellingen zijn op basis van multiqc 'Sequence
Quality Histograms' plot):

```{bash Trim1, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 8 ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/fastq/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/fastq/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic2/{}_paired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic2/{}_unpaired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic2/{}_paired.2.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic2/{}_unpaired.2.fastq ' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:30:10 ' \
                  'LEADING:30' \
                  'TRAILING:25'
```

Weer fastqc en multiqc gerund. De unpaired moeten niet worden meegenomen
in de analyse (dit zorgde namelijk voor een erg chaotisch multiqc
rapport). En threads meegeven, zodat het niet 3 uur duurt.

```{bash fastqc, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic2/*_paired.*  \
  -o /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/fastqc_after_trim2.2 -t 12
```

Trimmomatic met andere (strengere) settings gerund na overleg met de
groep:

```{bash trim2, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 10 ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/fastq/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/fastq/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_paired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_unpaired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_paired.2.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_unpaired.2.fastq ' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:30:10 ' \
                  'LEADING:32' \
                  'TRAILING:30'
```

In plaats van het fastqc rapport 'fastp' gebruikt op aanraden van Ramon,
omdat deze veel sneller gaat.

```{bash fastp, eval=FALSE}
ls /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3 | grep -i -E "*_paired*" | \
parallel "/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/tools/bin/falco /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{} -o /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/fastqc_after_trim3/{}_fastqc_report"
```

Daar weer multiqc op gedaan.

```{bash multiqc, eval=FALSE}
multiqc /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/fastqc_after_trim3/* \
-o /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/multiqc_after_trim3
```

De adapter ontent is erg hoog. Deze proberen te verminderen met headcrop
(begin eraf halen).

```{bash trim_headcrop, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/Transcriptomics/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 10 ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/fastq/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/fastq/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_paired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_unpaired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_paired.2.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/Transcriptomics/output/quality_control/trimmomatic3/{}_unpaired.2.fastq ' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:30:10 ' \
                  'HEADCROP:7' \
                  'LEADING:32' \
                  'TRAILING:30'
```

Na advies van Marcel te hebben gevraagd over het aantal adapter content
die we hebben tot de conclusie gekomen dat we waarschijnlijk geen
Trimmomatic hoeven te gebruiken (data is al goed genoeg). (!kijk nog
even naar de bron)

We zijn erachter gekomen dat in de NGS muizen geen menselijke cellen
zitten. Dus ook deze mappen tegen het muis-ref-genoom (Wat wel heel gek
is is dat in het artikel staat dat ze tegen het menselijke-ref-genoom
hebben gemapt, is dit een fout ?).\

