---
title: "Logbook Ramon Reilman"
author: "Ramon Reilman"
date: "2024-09-10"
output:
  html_document:
    toc: yes
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Logboek Ramon Reilman

## 10-9-2024

Bezig geweest met verschillende literatuur onderzoeken lezen.
Met de groep 1 van de door ons ingestuurde literatuur onderzoeken gekozen.

## 11-9-2024

Voor plan van aanpak en het nabootsen van het artikel moet er bekend zijn welke tools gebruikt zijn door het artikel.
Ik ben begonnen met dit uitzoeken door het artikel en dan vooral materiaal en methode te gaan lezen en verwerken.

## 12-9-2024

Vandaag verder gegaan met de gebruikte tools opsporen.
Ook heb ik gekeken wat voor type sequencing toegepast is (WES) en met welke sequencer (Illumina HiSeq 2500).
Alle gebruikte tools zijn gevonden en wat ze doen ook.

-   Burrows-Wheeler Aligner, voor de aligning van het DNA tegen het referentie genoom.
-   Picard, Het verwijderen van duplicaten en sorteren
-   Strelka, voor het vinden van mutaties
-   snpEff, informatie/impact van de mutaties op eiwitten

Nu kunnen we bezig met de tools verder uitzoeken en hun documentatie/installatie lezen.

## 13-9-2024

Dataset is gedownload naar de remote server, dit is uitgevoerd met het volgende command in bash:

```{bash, eval=FALSE}
prefetch $(</students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt) --output-directory \
 /students/2024-2025/Thema05/BlaasKanker/SRA/ --max-size 200G

```

Nu staat de data gedownload op de school server zodat we bezig kunnen met quality controle.

Verder bezig geweest met presentatie van het plan van aanpak voorbereiden.
Het lezen van de tools, en gebruik hiervan begrijpen.

## 14-9-2024

Plan van aanpak deadline dag, alle git branches zijn gemerged nadat feedback is gegeven en dit is aangepast.
Daarna zijn alle kopjes samengevoegd naar 1 bestand en deze is geknit tot pdf.

Janine heeft haar enkel gebroken, zal de presentatie missen en ik moet haar stukje last moment opvangen.

## 15-9-2024

De presentatie van het plan van aanpak is gemaakt.
Na nog wat feedback van de groepsgenoten is de achtergrond informatie iets meer uitgebreid.
Ook zijn spelfoutjes verwijderd en is de workflow flowchart een beetje aangepast (van nederlands naar engels).

## 16-9-2024

Presentatie van plan van aanpak gedaan.
Daarna zijn we bezig geweest met het "uitpakken" van de gedownloade SRR bestanden, dit moet omdat deze gecomprimeerd zijn.
Dit is gedaan met het volgende bash command.

```{bash , eval=FALSE}
find /students/2024-2025/Thema05/BlaasKanker/SRA/ -name "*.sra" | \
  parallel fasterq-dump -O /students/2024-2025/Thema05/BlaasKanker/fastq/ {}
```

Thuis ben ik bezig geweest met het kijken en proberen van testdata maken.
Testdata moet gemaakt worden om tools/commands te testen zonder dat deze uren, misschien wel dagen moeten draaien voordat ze een foutmelding geven.

De docent heeft ons verteld dat deze testdata gemaakt moet worden met seqkit split2 ik heb vervolgens een command gemaakt die dit gebruikt:

```{bash, eval=FALSE}
find /students/2024-2025/Thema05/BlaasKanker/fastq/ -name "*.fastq" -printf "%f\n" | \
  parallel seqkit split2 -O /students/2024-2025/Thema05/BlaasKanker/testdata/ -s 10000 -f {}
```

Het enige probleem met deze methode is dat het de fastq bestanden split op de -s N.
als een fastq file dan een miljoen reads heeft krijg je 1.000.000 / 10.000 bestanden.
Niet heel praktisch.

Nadat ik de documentatie van seqkit heb gelezen kwam ik uit bij seqkit sample.
seqkit sample bij het meegeven van een -n argument laad het hele fastq bestand in het geheugen, dat is onhandig bij hele grote fastq bestanden.

Op de website stond een methode die meer geheugen vriendelijk is, en hiermee heb ik een bash command gemaakt:

```{data, eval=FALSE}
find /students/2024-2025/Thema05/BlaasKanker/fastq/ -name "*.fastq" | \
  parallel "seqkit sample -p 0.1 {} | seqkit head -n 10000 > /students/2024-2025/Thema05/BlaasKanker/testdata/{/}"
```

Deze maakt testdata, van elk bestand 10.000 sequenties.

## 17-9-2024

Vandaag hebben wij een fastqc en multiqc uitgevoerd op onze test data.
Dit is gedaan om te bepalen wat de kwaliteit is van onze data.
En met deze informatie kan er met Trimmomatic de kwaliteit van de data verbeterd worden.

```{bash, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/testdata/* -o /students/2024-2025/Thema05/BlaasKanker/testingtools/fastqc/ -t 10
```

```{bash, eval=FALSE}
multiqc /students/2024-2025/Thema05/BlaasKanker/testingtools/fastqc/* -o /students/2024-2025/Thema05/BlaasKanker/testingtools/multiqc
```

Uit de plotjes bleek het volgende: De kwaliteit van de sequenties was goed, bij het begin en einde een beetje lager dan het midden, zoals verwacht.
Er zijn wel veel duplicaten, wat mogelijk kan komen doordat het een whole exome sequencing is, maar hier ga ik later onderzoek naar doen.

Verder heb ik deze dag en les Jasper en Iris geholpen met het uitvoeren van een fastqc en multiqc op onze data.

## 18-9-2024

Vandaag is gekeken naar de documentatie van Trimmomatic, ook heeft de docent er wat over uitgelegd.

We hebben een adapterfile gedownload om adapters uit onze sequenties te knippen.
En we hebben een Trimmomatic uitgevoerd, de settings hadden we gekregen van de docent.
Deze settings hebben wij niet aangepast, om te kijken wat het doet op onze data.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 8' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testingtools/testing_trim/{}_paired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testingtools/testing_trim/{}_unpaired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testingtools/testing_trim/{}_paired.2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testingtools/testing_trim/{}_unpaired.2.fastq' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:30:10' \
                  'LEADING:3' \
                  'TRAILING:3' \
                  'MINLEN:40 ' \
                  'SLIDINGWINDOW:4:20'
```

Hierna is een fastqc en multiqc uitgevoerd, en het bleek dat de kwaliteit van onze data verslechterd is.
Op alle vlakken.
Wij begrepen niet waarom, dus hebben wat settings weggehaald en het opnieuw uitgevoerd met andere settings.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 10' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/minlen_20/{}_paired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/minlen_20/{}_unpaired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/minlen_20/{}_paired.2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/minlen_20/{}_unpaired.2.fastq' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:30:10' \
                  'MINLEN:20'
```

Het uitvoeren van Trimmomatic, zelfs op data van 10.000 sequenties duurde ontzettend lang.
Wij begrijpen niet waarom.

De unpaired bestanden hadden 0 sequenties nadat we het met deze settings hebben uitgevoerd.
De unpaired bestanden die Trimmomatic maakt bevatten de sequenties van of de reverse of forward, waarbij de andere de kwaliteits controle niet gered heeft.

## 20-09-2024

Vandaag hebben wij aan de docent gevraagd hoe het dan dat de data een minder goede kwaliteit geeft.
Wij hebben de tip gekregen om goed na te denken over de settings, en goed de plotjes lezen van multiqc.
Op advies van de docent hebben we de testdata verhoogd naar 500.000 sequenties, zodat het ook tijdens het mappen duidelijker leesbaar wordt.

## 21-09-2024

Ik heb de plotjes gelezen van fastqc en multiqc, en heb op basis van dit nieuwe Trimmomatic experimenten uitgevoerd.

Ik wil trimmomatic uitvoeren die adapters weghaalt, een slidingwindow heeft van 4:20, en een minlen van 20.
Ik voer deze uit om te kijken hoe deze settings samen invloed heeft op de testdata in vergelijking tot de ongetrimde data.

| Run ID    | LEADING | TRAILING | SLIDING WINDOW | MINLEN | AVGQUAL | HEADCROP | CROP          | ILLUMINACLIP |
|-----------|---------|----------|----------------|--------|---------|----------|---------------|--------------|
| A4:20ML20 | NONE    | NONE     | 4:20           | 20     | NONE    | NONE     | TruSeq3-PE.fa |              |
|           |         |          |                |        |         |          |               |              |
|           |         |          |                |        |         |          |               |              |

Na een korte controle bleek onze adapter file niet goed te zijn, dit was door onbekende redenen een html file.
Dit kan eventueel verklaren waarom het zo lang duurde om Trimmomatic uit te voeren.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 12' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/trimmed_data/{}_paired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/trimmed_data/{}_unpaired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/trimmed_data/{}_paired.2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/trimmed_data/{}_unpaired.2.fastq' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:30:10' \
                  'MINLEN:20' \
                  'SLIDINGWINDOW:4:20'
```

Na het trimmen is de data met fastqc en multiqc verwerkt naar een webpagina met duidelijk leesbare plotjes.

```{bash, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/trimmed_data/* -o /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/fastqc -t 12

multiqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/fastqc* -o \
  /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/multiqc
```

Als ik kijk naar onze test data ongetrimmed ziet dat er erg goed uit.
het GC% ligt bij alle bestanden rond de 45% zoals verwacht.
De kwaliteit is goed, behalve aan het begin en einde, zoals verwacht.
Er zijn geen waarschuwingen, of adapters gevonden.
Dit laat mij denken dat we mogelijk de adapter optie weg kunnen laten.

Als ik vervolgens kijk naar de getrimmde data valt mij een aantal dingen op.
Er zijn 2 soorten output: paired en unpaired.
het aantal sequenties van paired is velen malen hoger dan de unpaired files.
Na het opzoeken wat deze files zijn kwam ik op het volgende: De .paired bestanden zijn bestanden waarin zowel de forward als reverse sequentie goed gekeurd zijn door Trimmomatics.
De .unpaired bestanden hebben de sequenties waarvan alleen dat bijpassende bestand goed gekeurd is door Trimmomatics.

Deze .unpaired bestanden hebben best wel een invloed op onze multiqc output, dus zal ik een multiqc uitvoeren op alleen de paired data.
Voor het onderzoek downstream lijkt mij het beste om mogelijk ook de unpaired sequenties achter te laten.
Dit zijn nu single end sequenties die een stuk lastiger zijn om te mappen.

## 22-09-2024

```{bash, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/trimmed_data/*_paired.* -o /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/output/fastqc_no_unpaired -t 12

multiqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/output/fastqc_no_unpaired/* -o \
  /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_20_ML20/output/multiqc_no_unpaired
```

De kwaliteit is niet veel verbeterd.

Het is goed om nu een stap terug te nemen en kijken naar de ongetrimde data.
Welke dingen kunnen verbeterd worden en welke trimmomatic settings kunnen hiervoor gebruikt worden?

Aan het begin en einde van de sequences is een verlaging van kwaliteit, deze is verwacht.
Dit kan verwijderd worden door leading en triailing.
Over de sequenties zijn een paar dips in kwaliteit zichtbaar, dit kan verwijderd worden door de sliding window.
Na het verwijderen is kan ik nog een MINLEN van 30, zodat de hele kleine sequenties verwijderd worden.
Adapter verwijderen is niet nodig, omdat er geen adapters gedetecteerd worden.

| Run ID          | LEADING | TRAILING | SLIDING WINDOW | MINLEN | AVGQUAL | HEADCROP | CROP          | ILLUMINACLIP |
|-----------------|---------|----------|----------------|--------|---------|----------|---------------|--------------|
| A4:20ML20       | NONE    | NONE     | 4:20           | 20     | NONE    | NONE     | TruSeq3-PE.fa |              |
| A4:32ML30L34T35 | 34      | 35       | 4:32           | 30     | NONE    | NONE     | NONE          |              |
|                 |         |          |                |        |         |          |               |              |

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 12' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/trimmed_data/{}_paired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/trimmed_data/{}_unpaired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/trimmed_data/{}_paired.2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/trimmed_data/{}_unpaired.2.fastq' \
                  'LEADING:34' \
                  'SLIDINGWINDOW:4:32' \
                  'TRAILING:35' \
                  'MINLEN:30'
```

## 22-09-2024

```{bash, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/trimmed_data/*_paired.* -o /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/output/fastqc -t 12

multiqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/output/fastqc/* -o \
  /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML30_L34_T35/output/multiqc
```

De kwaliteit van de sequentie is nu een zo goed als rechte lijn met een phred score van rond de 37.
De kans dat een nucleotide nu fout is is 0.000199526% (<https://eafyounian.github.io/phred_score_converter/>).
Het enige wat nu niet goed is is de distributie van de lengte.

## 23-09-2024

De kwaliteit is nu goed, alleen de verdeling van de lengtes van de sequenties is niet goed, al weet ik niet wat de oorzaak is.
Om te kijken of er verbetering is voer ik hetzelfde command uit met een hogere minlen.

| Run ID          | LEADING | TRAILING | SLIDING WINDOW | MINLEN | AVGQUAL | HEADCROP | CROP          | ILLUMINACLIP |
|-----------------|---------|----------|----------------|--------|---------|----------|---------------|--------------|
| A4:20ML20       | NONE    | NONE     | 4:20           | 20     | NONE    | NONE     | TruSeq3-PE.fa |              |
| A4:32ML30L34T35 | 34      | 35       | 4:32           | 30     | NONE    | NONE     | NONE          |              |
| A4:32ML50L34T35 | 34      | 35       | 4:32           | 50     | NONE    | NONE     | NONE          |              |
|                 |         |          |                |        |         |          |               |              |

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 12' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/testdata/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/trimmed_data/{}_paired.1.fastq ' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/trimmed_data/{}_unpaired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/trimmed_data/{}_paired.2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/trimmed_data/{}_unpaired.2.fastq' \
                  'LEADING:34' \
                  'SLIDINGWINDOW:4:32' \
                  'TRAILING:35' \
                  'MINLEN:50'
```

## 22-09-2024

```{bash, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/trimmed_data/*_paired.* -o /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/output/fastqc -t 12

multiqc /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/output/fastqc/* -o \
  /students/2024-2025/Thema05/BlaasKanker/trimmingtesting/A4_32_ML50_L34_T35/output/multiqc
```

Hieruit blijkt nogsteeds een incorrecte verdeling te zijn van de lengtes van sequenties.
Ik zal ergens deze week vragen naar een oplossing hiervoor.

## 23-09-2024

Vandaag zijn we bezig geweest met het mappen via bwa, zie hiervoor Jasper zijn logboek.

Ik ben daarnaast bezig geweest met het installeren van Strelka.
Strelka is een software die wij gaan gebruiken om varianten te vinden in onze data.
Deze staat niet standaard op de server, dus zal ik handmatig moeten installeren.
### Strelka installeren Download the strelka git:

```{bash, eval=FALSE}
wget "https://github.com/Illumina/strelka/releases/download/v2.9.10/strelka-2.9.10.centos6_x86_64.tar.bz2"
tar xvjf strelka-2.9.10.centos6_x86_64.tar.bz2
```

Er wordt aangeraden om te testen of de software werkt

```{bash, eval=FALSE}
bash strelka-2.9.10.centos6_x86_64/bin/runStrelkaSomaticWorkflowDemo.bash
```

Hieruit blijkt dat ik python2 nodig heb.

Na korte research heb ik gevonden dat ik python versies lokaal kan installeren met pyenv.

```{bash, eval=FALSE}
git clone https://github.com/pyenv/pyenv.git
```

Nu staat pyenv in onze tools folder, en kan deze gebruikt worden om andere python versies te installeren.
1 groot probleem is dat pyenv in de gebruikers home dingen installeerd, dat wil ik niet aangezien de home folder maar 25 gigabytes mag zijn.
Ik moet in mijn \~/.bashrc bestand dus een andere locatie aangeven voor pyenv.

```{bash, eval=FALSE}
export PYENV_ROOT="/students/2024-2025/Thema05/BlaasKanker/tools/python_versies"
export PATH="$PYENV_ROOT/bin:$PATH"

eval "$(/students/2024-2025/Thema05/BlaasKanker/tools/pyenv/bin/pyenv init --path)"
export PYENV_CACHE_PATH="/students/2024-2025/Thema05/BlaasKanker/tools/.pyenvcache/"
```

Op deze manier kan ik een dir meegeven waar ik de versies wil hebben.
Nu kan ik een python versie installeren.

```{bash, eval=FALSE}
/students/2024-2025/Thema05/BlaasKanker/tools/pyenv/bin/pyenv install 2.7
/students/2024-2025/Thema05/BlaasKanker/tools/pyenv/bin/pyenv global 2.7
pip2.7 install virtualenv
python2.7 -m virtualenv strelkaVENV
```

Nu hebben we een virtualenv van python 2.7 in onze tools folder.
Hier kunnen we de benodigde pakketjes installeren, die ook gebruikt kunnen worden door mijn groeps genoten.

## 24-09-2024

Omdat er een aantal duplicaten zijn, die mogelijk een negatieve impact kunnen hebben bij variant calling (kan een bias veroorzaken) Gaan wij deze duplicaten verwijderen met picard.
Vandaag ga ik de documentatie lezen en kijken of ik de tool werkend kan krijgen.
<!-- TODO ref naar jaspers logboek --> 
Eerst heb ik Jasper zijn logboek gevolgd om een index te maken, en de fastq files te mappen naar het referentie genoom.
Daarna heb ik picard gerund op 1 van de outputs, als test.
Deze gaf meerdere foutmeldingen.

```{bash, eval=FALSE}
java -jar picard.jar MarkDuplicates \
  "I=/students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/SRR14870694_sorted.bam" \
  "O=/students/2024-2025/Thema05/BlaasKanker/temp/picard_test/duplicates.bam" \
  "M=/students/2024-2025/Thema05/BlaasKanker/temp/picard_test/duplicates.txt" \
```

Een van deze foutmeldingen was dat de naam van het input bestand niet correct was.
Na een google search heb ik een oplossing gevonden hiervoor.

```{bash, eval=FALSE}
java -jar picard.jar MarkDuplicates \
  "I=/students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/SRR14870694_sorted.bam" \
  "O=/students/2024-2025/Thema05/BlaasKanker/temp/picard_test/duplicates.bam" \
  "M=/students/2024-2025/Thema05/BlaasKanker/temp/picard_test/duplicates.txt" \
  "READ_NAME_REGEX=null"
```

Nu maakt de naam van het input bestand niet uit.

Een volgende error had een iets andere oplossing.
In de bam files mist een @RG header, deze header geeft groep, ID, platofrm en library aan van de samples.
En deze header heeft picard nodig om het input bestand te lezen.
Deze kan je meegeven aan bwa mem tijdens het mappen, de aangepaste commands staan hier onder.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel -j 20 "bwa mem -t 20 -M -R '@RG\\tID:{}\\tSM:{}\\tPL:illumina\\tLB:lib1' \
    /students/2024-2025/Thema05/BlaasKanker/tools/testGenome/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna \
    /students/2024-2025/Thema05/BlaasKanker/outputs/fastq/{}_1.fastq /students/2024-2025/Thema05/BlaasKanker/outputs/fastq/{}_2.fastq > \
    /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/first_output/{}.sam"

```

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel "samtools view -b /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/first_output/{}.sam | samtools sort -o /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/{}_sorted.bam"
```

Jasper heeft deze stap in 2 gesplitst, maar voeg ik samen zodat het meer hands off is voor mij.

```{bsah, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel -j 6 "samtools index /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_output/{}.sorted.bam"
```

Ook deze bestanden moeten met samtools index gedaan worden, het bestand wat hier uitkomt heeft picard ook nodig.

<!-- TODO Log deze secties. -->

Nu kan de test met picard weer uitgevoerd worden.

```{bash, eval=FALSE}
java -jar picard.jar MarkDuplicates \
  "I=/students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/SRR14870694_sorted.bam" \
  "O=/students/2024-2025/Thema05/BlaasKanker/temp/picard_test/duplicates.bam" \
  "M=/students/2024-2025/Thema05/BlaasKanker/temp/picard_test/duplicates.txt" \
  "READ_NAME_REGEX=null"
```

Het uitput bestand is gemaakt, en bevat duplicaten die een mark hebben.
Zo kunnen tools downstream deze vermijden.

## 25-09-2024

Vandaag wil ik gaan kijken naar hoe we strelka moeten gebruiken.
Eerder in het logboek heb ik uitgelegd hoe die geinstalleerd is met python2.7 Op de officiele website kon ik zo'n soort gelijk bestand vinden.
Alleen is er een probleem.
Onze tumor is ingebracht, en heft niks te maken met de germline.
Opzich is dit geen probleem, want strelka heeft een somatische workflow.
Alleen hebben wij de .bam file nodig van een normale muis, zonder de tumor.
In het artikel staat wel benoemd dat ze die hebben, maar ik kon deze files nergens vinden.
Ik heb het contact persoon een mail gestuurd, en we hopen en wachten nu op een antwoord.

Deze konden wij dus niet uitvoeren zonder normal file.

```{bash, eval=FALSE}
python2.7 /students/2024-2025/Thema05/BlaasKanker/tools/strelka-2.9.10.centos6_x86_64/bin/configureStrelkaSomaticWorkflow.py \
    --tumorBam /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/SRR14870694_sorted.bam \
    --referenceFasta /students/2024-2025/Thema05/BlaasKanker/tools/testGenome/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna \
    --runDir /students/2024-2025/Thema05/BlaasKanker/temp/demo_somatic

```

Het probleem bij het uitvoeren van dit command is dat alle erfbare mutaties ook gemarkeerd worden.
Het is vervolgens erg lastig om de germline en somatische mutaties uit elkaar te halen.

```{bash, eval=FALSE}
python2.7 /students/2024-2025/Thema05/BlaasKanker/tools/strelka-2.9.10.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py     --bam /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/SRR14870694_sorted.bam     --referenceFasta /students/2024-2025/Thema05/BlaasKanker/tools/testGenome/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna     --runDir /students/2024-2025/Thema05/BlaasKanker/temp/demo_somatic
```

Dit command werkte niet, er miste een bestand bij het referentie genoom.
Deze kan aangemaakt worden met de volgende samtool feature.

```{bash, eval=FALSE}
samtools faidx GCF_000001635.27_GRCm39_genomic.fna
```

Command is weer uitgevoerd, en nu kregen we een output bestand.
Helaas heb ik nog niks gehoord van het contact persoon, en zal de 27e advies vragen aan de docenten.

```{bash, eval=FALSE}
python2.7 /students/2024-2025/Thema05/BlaasKanker/tools/strelka-2.9.10.centos6_x86_64/bin/configureStrelkaGermlineWorkflow.py     --bam /students/2024-2025/Thema05/BlaasKanker/temp/mappingTest/sorted_bam/SRR14870694_sorted.bam     --referenceFasta /students/2024-2025/Thema05/BlaasKanker/tools/testGenome/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna     --runDir /students/2024-2025/Thema05/BlaasKanker/temp/demo_somatic
```

### Official trim

Deze week gaan wij mappen en duplicaten markeren, maar daarvoor moeten we eerst zeker zijn of we de ongetrimde data gaan gebruiken of wel getrimde data.

| Run ID   | LEADING | TRAILING | SLIDING WINDOW | MINLEN | AVGQUAL | HEADCROP | CROP | ILLUMINACLIP  |
|----------|---------|----------|----------------|--------|---------|----------|------|---------------|
| FinalRun | 34      | 34       | NONE           | 40     | NONE    | NONE     | None | TruSeq3-PE.fa |
|          |         |          |                |        |         |          |      |               |
|          |         |          |                |        |         |          |      |               |

Waarom hebben we deze settings gekozen?
De kwaliteit in het midden van de sequenties is rond de 35, er wijkt zo weinig van af dat een sliding window niet nodig is.
Aan het begin en eind dipt de kwaliteit iets wat naar de 32, deze halen wij voor de zekerheid weg, maar meer niet.
Zo blijft de lengte van de sequenties lang genoeg om goed te kunnen mappen.
Ook halen wij de adapters weg voor de zekerheid, als er 1 of 2 toch zijn worden die dan verwijderd.
De sliding window wordt ook niet gebruikt omdat deze er voor zorgt dat er veel meer korte sequenties zijn, wat onnodig is aangezien de kwaliteit al goed is.
MINLEN van 40 zorgt ervoor dat er niet te korte reads zijn die bij downstream workflows mogelijk problemen kunnen veroorzaken, of gewoon lastiger zijn om te gebruiken.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
  parallel 'TrimmomaticPE -threads 20' \
                  '/students/2024-2025/Thema05/BlaasKanker/outputs/fastq/{}_1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/outputs/fastq/{}_2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/outputs/fastq_trimmed/{}_paired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/outputs/fastq_trimmed/{}_unpaired.1.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/outputs/fastq_trimmed/{}_paired.2.fastq' \
                  '/students/2024-2025/Thema05/BlaasKanker/outputs/fastq_trimmed/{}_unpaired.2.fastq' \
                  'ILLUMINACLIP:/students/2024-2025/Thema05/BlaasKanker/tools/trim_adapters/TruSeq3-PE.fa:2:20:10' \
                  'LEADING:34' \
                  'TRAILING:34' \
                  'MINLEN:40'

```

Voor het mappen met BWA, zullen we eerst nog even snel kijken naar de kwaliteit.

```{bash, eval=FALSE}
fastqc /students/2024-2025/Thema05/BlaasKanker/outputs/fastq_trimmed/*_paired* -o /students/2024-2025/Thema05/BlaasKanker/outputs/fastqc_trimmed/ -t 15

multiqc /students/2024-2025/Thema05/BlaasKanker/outputs/fastqc_trimmed/*_paired* -o /students/2024-2025/Thema05/BlaasKanker/outputs/multiqc_trimmed
```

De kwaliteit van de sequenties ligt tussen de 35 en 37, wat goed is. de kans dat een nucleotide incorrect is ligt tussen de 0.000316228 en 0.000199526 (<https://eafyounian.github.io/phred_score_converter/>).
Er worden ook geen adapters gevonden.
Er zijn nu wel een aantal kortere sequenties, maar de meeste liggen nog tussen de 90-95, de te korte sequenties van 40 en daaronder zijn wel verwijderd.
Zo krijgen we sequenties van hoge kwaliteit die toch nog goed gemapped kunnen worden.

## 26-09-2024

Vandaag voeren wij de BWA mapping uit <!-- TODO Ref naar Jasper, plaats commands -->

## 27-09-2024
Omdat wij geen normaal data hebben is het uitvoeren van een somatische variant call onmogelijk.
Dit is een groot probleem omdat de erfbare mutaties nu ook gecalled zullen worden, en we mogelijke honderd duizenden mutaties krijgen. Om vervolgens dan de tumor mutaties vinden is lastig, mogelijk zelfs onmogelijk in de korte tijd die wij hebben.

Ik heb de schrijvers van het artikel gemailed, en zij zijn nu aan het kijken of er wat gedaan kan worden.
Er moet toch een eindproduct komen. We zullen dus met een meer generieke variant calling tool bezig gaan. Lofreq
<!-- TODO vraag jasper permissie -->
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel "lofreq call \
    -f /students/2024-2025/Thema05/BlaasKanker/outputs/bwa_aln/index/GCF_000001635.27_GRCm39_genomic.fna \
    -o /students/2024-2025/Thema05/BlaasKanker/testingtools/test_variant_calling/{}_variants.vcf \
    /students/2024-2025/Thema05/BlaasKanker/testingtools/picard_test/poging_1/{}.marked_duplicates.bam"
```
De reference heeft een ander bestand nodig

```{bash, eval=false}
samtools faidx /students/2024-2025/Thema05/BlaasKanker/outputs/bwa_aln/index/GCF_000001635.27_GRCm39_genomic.fna

```
Na dit uitgevoerd te hebben kan lofreq weer, zonder enige specifieke instellingen zodat Janine kan oefenen met snpeff dit weekend.

## 01-10-2024

Vandaag ga ik van bij alle data met lofreq de variant calling uitvoeren, zo krijgen we bestanden waarin alle mutaties van de muizen staan in verhouding tot de reference genome.
Hierbij zullen dus ook de erfelijke mutaties meegenomen worden, omdat we geen sequence data van gezonde muizen hebben.
Ik hoef geen settings mee te geven voor de kwaliteit van de data, en ook voor de output hoef ik nu geen filter stappen toe te voegen, het filteren wordt gedaan met een andere tool later deze week.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel "lofreq call \
    -f /students/2024-2025/Thema05/BlaasKanker/outputs/bwa_aln/index/GCF_000001635.27_GRCm39_genomic.fna \
    -o /students/2024-2025/Thema05/BlaasKanker/outputs/variant_calling_unfiltered/{}_variants.vcf \
    --verbose \
    /students/2024-2025/Thema05/BlaasKanker/outputs/picard_dub/marked_duplicates/{}.marked_duplicates.bam"
```

Omdat het we straks ontzettend veel varianten krijgen leek het mij een goed idee om vandaag te kijken naar het filteren van de annotaties.
SNPeff kan doormiddel van bestand met gene symbols als het goed is zoeken naar die genen.
Ik heb op https://www.informatics.jax.org/mgihome/homepages/help.shtml gezocht naar genen die met blaaskanker te maken hebben.

Deze lijst kan je downloaden, maar er staat veel overbodige informatie in. Daarom heb ik een scriptje in python geschreven die de genen er uit kan halen. zie main src/python.
Als Janine straks klaar is met annotatie, kunnen we op die manier filteren.

Janine loopt vast met snpEff, er zijn probelemen met MT tabellen?
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel -j 8 \
    "java -Xmx8g -jar /students/2024-2025/Thema05/BlaasKanker/tools/snpeff/snpEff/snpEff.jar ann -v -stats \
    /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/stats.html mm39 \
    /students/2024-2025/Thema05/BlaasKanker/outputs/variant_calling_unfiltered/{}_variants.vcf > /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/{}.vcf"
```
Heb op github een zelfde soort issue gevonden, die heb gevolgd en dat probleem was vervolgens opgelost.
https://github.com/pcingola/SnpEff/issues/536#issuecomment-2189201996
Dankjewel lukedow.


Daarna heb ik snpeff weer uitgevoerd. Maar toen ontstond er het volgende probleem, de chromosoom benaming in de vcf bestanden en de net gebouwde data base komen niet overeen. Ik hen online op ncbi een mapje gevonden die de ncbi benaming omzet naar chromosome nummers, zie etc/chromosome_map.txt
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
parallel -j 8 \
"bcftools annotate --rename-chrs /students/2024-2025/Thema05/BlaasKanker/etc/chromosome_map.txt /students/2024-2025/Thema05/BlaasKanker/outputs/variant_calling_unfiltered/{}_variants.vcf > /students/2024-2025/Thema05/BlaasKanker/outputs/calling_renamed/{}_variants.vcf"

```
Hierna kreeg ik de volgende foutmelding, geen idee wat het inhoud maar er was een quick workaround voor
'Contig 'NC_000067.7' is not defined in the header. (Quick workaround: index the file with tabix.'


Ik heb voor de zekerheid een backup gemaakt van de variant calling data, en het volgende command uitgevoerd.
Die zou een index van de file moeten maken
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
parallel -j 8 \
"tabix -p vcf {}_variants.vcf"
```
Hier kwam nog een foutmelding uit, de bestanden moesten compressed zijn.
'[tabix] the compression of 'SRR14870694_variants.vcf' is not BGZF'

Ik heb de bestanden dus eerst met bgzip omgezet naar bestanden die compressed zijn
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
parallel -j 8 \
"bgzip -c {}_variants.vcf > {}_variants.vcf.gz"
```

Hierna opnieuw de index met tabix uitgevoerd.
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
parallel -j 8 \
"tabix -p vcf {}_variants.vcf.gz"
```
Dit werkt ook niet: 'Contig 'NC_000067.7' is not defined in the header. (Quick workaround: index the file with tabix.'

Uiteindelijk bleek ik dus dat ik de header opnieuw moest maken van elk bestand met de .fai versie van onze referentie genoom.
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel -j 8 \
    "bcftools reheader --fai /students/2024-2025/Thema05/BlaasKanker/tools/testGenome/ncbi_dataset/data/GCF_000001635.27/GCF_000001635.27_GRCm39_genomic.fna.fai \
    -o /students/2024-2025/Thema05/BlaasKanker/outputs/calling_renamed/{}_remade.vcf \
    /students/2024-2025/Thema05/BlaasKanker/outputs/variant_calling_unfiltered/{}_variants.vcf"


```
Dit heeft vervolgens wel gewerkt.

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
parallel -j 8 \
"bcftools annotate --rename-chrs /students/2024-2025/Thema05/BlaasKanker/etc/chromosome_map.txt /students/2024-2025/Thema05/BlaasKanker/outputs/calling_renamed/{}_remade.vcf > /students/2024-2025/Thema05/BlaasKanker/outputs/chromosome_remade_varients/{}_variants.vcf"
```
En daardoor kon ik de namen van de chromosomen omzetten met de chromosome map.
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel -j 8 \
    "java -Xmx8g -jar /students/2024-2025/Thema05/BlaasKanker/tools/snpeff/snpEff/snpEff.jar ann -v -stats \
    /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/stats.html mm39 \
    /students/2024-2025/Thema05/BlaasKanker/outputs/chromosome_remade_varients/{}_variants.vcf > /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/{}.vcf"
```

Eindelijk kon ik met snpEff toch wel de variant annotatie uitvoeren.
Deze geeft een tabel met chromosomen met een n van aantal variants.
In deze tabel staan een aantal NT_*** chromosomen, die ik niet ken en niet voorkomen in mijn chromosome map. Morgen zal ik hier verder naar kijken.

## 02-10-2024
Ik heb op de website hieronder een downloadbare tabel kunnen vinden die ook de meest NT_*** chromosomen kan mappen
https://www.ncbi.nlm.nih.gov/datasets/genome/GCF_000001635.27/

Ik heb dus weer de namen veranderd in mijn variant calling bestanden
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
parallel -j 8 \
"bcftools annotate --rename-chrs /students/2024-2025/Thema05/BlaasKanker/etc/chromey_map_updated.txt /students/2024-2025/Thema05/BlaasKanker/outputs/calling_renamed/{}_remade.vcf > /students/2024-2025/Thema05/BlaasKanker/outputs/chromosome_remade_varients/{}_variants.vcf"
```

snpEff weer uitgevoerd.
```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel -j 8 \
    "java -Xmx8g -jar /students/2024-2025/Thema05/BlaasKanker/tools/snpeff/snpEff/snpEff.jar ann -v -stats \
    /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/stats.html mm39 \
    /students/2024-2025/Thema05/BlaasKanker/outputs/chromosome_remade_varients/{}_variants.vcf > /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/{}.vcf"
```
Er stonden nu een aantal CHROMOSOME_Not_found errors, en een UN in de tabel.
De UN staat dus voor unkown gedeelte, en kan dus niet gemapt worden aan een bestaand chromosoom. Deze veroorzaakt ook de CHROMOSOME_Not_found errors.


### Vsualisatie:
https://cmdcolin.github.io/awesome-genome-visualization/?language=R&latest=true&platform=&tag=GWAS


## 3-10-2024
Waarschijnlijk hebben we een BED file nodig met chromsomen, exon posities en genen voor de visualisatie. Die hebben wij op dit moment niet, dus ik zal deze voor het mm39 muis referentie genoom genereren.

Voor het genereren van een BED file hebben we een GTF bestand nodig, deze bevat alle data die we nodig hebben

```{bash, eval=FALSE}

wget https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/gencode.vM35.annotation.gtf.gz

```

Dit bestand staat vol met data die ik niet nodig heb, als het goed is kan ik met een python scriptje hier de belangrijke data wel uithalen
Het python scriptje kan dus GTF bestanden omzetten naar bed bestanden met de data die wij nodig hebben.

snpEff geeft nog wel een aantal warnings weer

WARNING_TRANSCRIPT_INCOMPLETE   5223
WARNING_TRANSCRIPT_MULTIPLE_STOP_CODONS 63
WARNING_TRANSCRIPT_NO_START_CODON       3093
WARNING_TRANSCRIPT_NO_STOP_CODON        2347
Na de warnings te lezen op de website van snpEff blijkt dit te liggen aan onze gebouwde database.

Ik zal nog 1 keer proberen de database opnieuw te bouwen, volgens de website van snpEff

```{basj, eval=FALSE}
cd snpeff/snpEff/data
mkdir mm39; cd mm39

wget https://ftp.ensembl.org/pub/current/gtf/mus_musculus/Mus_musculus.GRCm39.112.gtf.gz
mv Mus_musculus.GRCm39.112.gtf.gz genes.gtf.gz

mkdir /snpeff/snpEff/data/genome
cd /snpeff/snpEff/data/genome

wget https://ftp.ensembl.org/pub/current/fasta/mus_musculus/dna/Mus_musculus.GRCm39.dna.toplevel.fa.gz
mv Mus_musculus.GRCm39.dna.toplevel.fa.gz mm39.fa.gz
gzip -d de bestanden
java -jar snpEff.jar build -gtf22 -v mm39
```
Nieuwe database is gebouwd


```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel -j 6 \
    "java -Xmx8g -jar /students/2024-2025/Thema05/BlaasKanker/tools/snpeff/snpEff/snpEff.jar ann -nodownload -v -stats \
    /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/stats.html mm39 \
    /students/2024-2025/Thema05/BlaasKanker/outputs/chromosome_remade_varients/{}_variants.vcf > /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/{}.vcf"

```

Deze manier van het bouwen van een database voor mm39 werkt niet.
Ik blijf de vorige gebruiken. De waarschuwingen kunnen voorkomen wanneer het genoom niet helemaal gebrepen is, en dat kan aangezien we ook Unkown chromosome maps hebben.

Ik zal nu eerst filteren naar de genen die ik heb gevonden op MGI
```{bash, eval=FALSE}
python3 parse_mgi.py ../../data/MGI_file.txt --output_file /students/2024-2025/Thema05/BlaasKanker/etc/gene_file.txt
```
Zet MGI feature file om naar een bestand met gene names

```{bash, eval=FALSE}
cat /students/2024-2025/Thema05/BlaasKanker/SRR_Acc_List.txt | \
    parallel -j 8 \
    "vcftools --vcf /students/2024-2025/Thema05/BlaasKanker/temp/annoting_test/{}.vcf --keep /students/2024-2025/Thema05/BlaasKanker/etc/gene_file.txt --recode --out /students/2024-2025/Thema05/BlaasKanker/temp/marked_cancer/{}"

```

Er zijn 0 varianten over gebleven, om te controleren of het filteren werkt filter ik op 1 gen wararvan ik wee dat deze in een vcf bestand voor komt

```{bash, eval=FALSE}
bcftools view --include 'INFO == "Xkr4"' SRR14870694.vcf > test_sample.vcf
```
Om te testen of deze echt wel bestaat
[filter.c:2933 filters_init1] Error: the tag "INFO" is not defined in the VCF header
De info header heeft een ID voor gene naam

```{bash, eval=FALSE}
grep ^# SRR14870694.vcf
```
Hieruit kan ik de naam vinden voor geen naam bij INFO
Omdat ik er niet zeker van kan zijn dat de bcftools wel goed zoekt en vcftools wel goed filterd ga ik mijn eigen scriptje schrijven die genen uit een txt bestand kan vinden in een vcf bestand.


